apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/component: notifications
data:
  mongodb.database: "hopngo_notifications"
  rabbitmq.host: "rabbitmq"
  rabbitmq.port: "5672"
  application.yml: |
    server:
      port: 8089
    spring:
      application:
        name: notification-service
      profiles:
        active: k8s
      data:
        mongodb:
          database: hopngo_notifications
      rabbitmq:
        port: 5672
        virtual-host: /
        connection-timeout: 15000
        template:
          retry:
            enabled: true
            initial-interval: 1000
            max-attempts: 3
            multiplier: 2
        listener:
          simple:
            retry:
              enabled: true
              initial-interval: 1000
              max-attempts: 3
              multiplier: 2
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      endpoint:
        health:
          probes:
            enabled: true
          show-details: always
    jwt:
      public-key-location: classpath:jwt-public.key
    firebase:
      project-id: hopngo-notifications
    logging:
      level:
        com.hopngo.notification: INFO
        org.springframework.amqp: DEBUG
        com.google.firebase: DEBUG