apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/component: notifications
spec:
  type: ClusterIP
  ports:
  - port: 8089
    targetPort: 8089
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: notification-service