# Development profile configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hopngo
    username: hopngo
    password: hopngo_dev_2024!
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: true
  
  # Disable Redis for development
  cache:
    type: simple
  
  # Disable RabbitMQ for development
  cloud:
    stream:
      default-binder: rabbit
      bindings:
        payment-events-out-0:
          destination: payment.events
          binder: test
        order-events-out-0:
          destination: order.events
          binder: test
      test:
        binder:
          type: test
  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    com.hopngo.market: DEBUG
    org.springframework.cache: INFO
    org.springframework.data.redis: INFO
    org.h2: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE