server:
  port: 8084

spring:
  application:
    name: market-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/hopngo_market
    username: hopngo
    password: hopngo123
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  
  cache:
    type: redis
    redis:
      time-to-live: 600000  # 10 minutes
  
  cloud:
    stream:
      bindings:
        payment-events-out-0:
          destination: payment.events
          content-type: application/json
        order-events-out-0:
          destination: order.events
          content-type: application/json
      rabbit:
        bindings:
          payment-events-out-0:
            producer:
              routing-key-expression: "'payment.' + payload.eventType.replace('.', '_')"
              exchange-type: topic
          order-events-out-0:
            producer:
              routing-key-expression: "'order.' + payload.eventType.replace('.', '_')"
              exchange-type: topic
        binder:
          connection-name-prefix: market-service
  
  rabbitmq:
    host: localhost
    port: 5672
    username: hopngo
    password: hopngo123

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.hopngo.market: DEBUG
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  info:
    title: HopNGo Market Service API
    description: API for marketplace functionality including products, orders, and payments
    version: 1.0.0