# cert-manager ClusterIssuer for Let's Encrypt production certificates
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: cluster-issuer
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@hopngo.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@hopngo.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
          ingressTemplate:
            metadata:
              annotations:
                nginx.ingress.kubernetes.io/whitelist-source-range: "0.0.0.0/0"
---
# Certificate resource for automatic TLS certificate management
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: production-hopngo-tls
  namespace: hopngo-prod
  labels:
    app.kubernetes.io/name: hopngo-tls
    app.kubernetes.io/component: certificate
spec:
  secretName: production-hopngo-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - hopngo.com
  - www.hopngo.com
  - api.hopngo.com