apiVersion: v1
kind: Namespace
metadata:
  name: hopngo-prod
  labels:
    name: hopngo-prod
    environment: production
    # Pod Security Standards labels
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted