# Production secrets configuration
# Uses external secret management and removes plaintext secrets

# External Secrets Operator configuration for Google Secret Manager
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: hopngo-secret-store
  namespace: hopngo-prod
  labels:
    app.kubernetes.io/name: secret-store
    app.kubernetes.io/component: secrets
spec:
  provider:
    gcpsm:
      projectID: "hopngo-production"
      auth:
        workloadIdentity:
          clusterLocation: us-central1
          clusterName: hopngo-prod-cluster
          serviceAccountRef:
            name: external-secrets-sa
---
# External Secret for database credentials
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: database-secret
  namespace: hopngo-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: hopngo-secret-store
    kind: SecretStore
  target:
    name: database-secret
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: hopngo-prod-db-username
  - secretKey: password
    remoteRef:
      key: hopngo-prod-db-password
---
# External Secret for MongoDB credentials
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-secret
  namespace: hopngo-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: hopngo-secret-store
    kind: SecretStore
  target:
    name: mongodb-secret
    creationPolicy: Owner
  data:
  - secretKey: connection-string
    remoteRef:
      key: hopngo-prod-mongodb-connection
---
# External Secret for Redis credentials
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-secret
  namespace: hopngo-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: hopngo-secret-store
    kind: SecretStore
  target:
    name: redis-secret
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: hopngo-prod-redis-password
---
# External Secret for RabbitMQ credentials
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rabbitmq-secret
  namespace: hopngo-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: hopngo-secret-store
    kind: SecretStore
  target:
    name: rabbitmq-secret
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: hopngo-prod-rabbitmq-username
  - secretKey: password
    remoteRef:
      key: hopngo-prod-rabbitmq-password
---
# External Secret for JWT keys
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jwt-secret
  namespace: hopngo-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: hopngo-secret-store
    kind: SecretStore
  target:
    name: jwt-secret
    creationPolicy: Owner
  data:
  - secretKey: private-key
    remoteRef:
      key: hopngo-prod-jwt-private-key
  - secretKey: public-key
    remoteRef:
      key: hopngo-prod-jwt-public-key
---
# External Secret for payment provider keys
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: payment-secret
  namespace: hopngo-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: hopngo-secret-store
    kind: SecretStore
  target:
    name: payment-secret
    creationPolicy: Owner
  data:
  - secretKey: stripe-secret-key
    remoteRef:
      key: hopngo-prod-stripe-secret-key
  - secretKey: stripe-webhook-secret
    remoteRef:
      key: hopngo-prod-stripe-webhook-secret
  - secretKey: bkash-app-key
    remoteRef:
      key: hopngo-prod-bkash-app-key
  - secretKey: bkash-app-secret
    remoteRef:
      key: hopngo-prod-bkash-app-secret
  - secretKey: nagad-merchant-id
    remoteRef:
      key: hopngo-prod-nagad-merchant-id
  - secretKey: nagad-merchant-key
    remoteRef:
      key: hopngo-prod-nagad-merchant-key
---
# External Secret for OpenAI API key
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openai-secret
  namespace: hopngo-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: hopngo-secret-store
    kind: SecretStore
  target:
    name: openai-secret
    creationPolicy: Owner
  data:
  - secretKey: api-key
    remoteRef:
      key: hopngo-prod-openai-api-key
---
# External Secret for Google Maps API key
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: maps-secret
  namespace: hopngo-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: hopngo-secret-store
    kind: SecretStore
  target:
    name: maps-secret
    creationPolicy: Owner
  data:
  - secretKey: google-api-key
    remoteRef:
      key: hopngo-prod-google-maps-api-key
---
# External Secret for Firebase credentials
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firebase-secret
  namespace: hopngo-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: hopngo-secret-store
    kind: SecretStore
  target:
    name: firebase-secret
    creationPolicy: Owner
  data:
  - secretKey: credentials
    remoteRef:
      key: hopngo-prod-firebase-credentials
---
# External Secret for frontend NextAuth
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frontend-secret
  namespace: hopngo-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: hopngo-secret-store
    kind: SecretStore
  target:
    name: frontend-secret
    creationPolicy: Owner
  data:
  - secretKey: nextauth-secret
    remoteRef:
      key: hopngo-prod-nextauth-secret
---
# Service Account for External Secrets Operator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: hopngo-prod
  annotations:
    iam.gke.io/gcp-service-account: external-secrets@hopngo-production.iam.gserviceaccount.com