server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/users/**
          filters:
            - name: JwtAuthenticationFilter
        - id: social-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/posts/**,/api/comments/**
          filters:
            - name: JwtAuthenticationFilter
        - id: trip-planning-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/trips/**,/api/itineraries/**
          filters:
            - name: JwtAuthenticationFilter
        - id: ai-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/ai/**
          filters:
            - name: JwtAuthenticationFilter
        - id: emergency-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/emergency/**
          filters:
            - name: JwtAuthenticationFilter
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false

jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}

logging:
  level:
    com.hopngo.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG