server:
  port: 8087

spring:
  application:
    name: trip-planning-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/hopngo
    username: hopngo
    password: hopngo_dev_2024!
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
  
  flyway:
    enabled: false

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  info:
    title: Trip Planning Service API
    description: AI-assisted trip planning and itinerary management
    version: 1.0.0

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Logging configuration
logging:
  level:
    com.hopngo.tripplanning: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Application specific configuration
app:
  ai-service:
    url: http://localhost:8088
    timeout: 30000
  trip-planning:
    max-days: 30
    min-days: 1
    max-destinations: 10