server:
  port: 8083

spring:
  application:
    name: booking-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/hopngo_booking
    username: hopngo
    password: hopngo_dev_2024!
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: false
  
  cloud:
    stream:
      bindings:
        bookingEvents-out-0:
          destination: booking.events
          content-type: application/json
        paymentEvents-in-0:
          destination: payment.events
          content-type: application/json
          group: booking-service
      rabbit:
        bindings:
          bookingEvents-out-0:
            producer:
              routing-key-expression: headers['eventType']
          paymentEvents-in-0:
            consumer:
              binding-routing-key: 'payment.succeeded,payment.failed'
              auto-bind-dlq: true
              republish-to-dlq: true
              max-attempts: 3
      function:
        definition: bookingEvents;paymentEventHandler
  
  rabbitmq:
    host: localhost
    port: 5672
    username: hopngo
    password: rabbit_dev_2024!
    virtual-host: hopngo

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.hopngo.booking: DEBUG
    org.springframework.cloud.stream: DEBUG