server:
  port: 8083

spring:
  application:
    name: booking-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/hopngo
    username: hopngo_user
    password: hopngo_password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  
  cloud:
    stream:
      bindings:
        bookingEvents-out-0:
          destination: booking.events
          content-type: application/json
      rabbit:
        bindings:
          bookingEvents-out-0:
            producer:
              routing-key-expression: headers['eventType']
      function:
        definition: bookingEvents
  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.hopngo.booking: DEBUG
    org.springframework.cloud.stream: DEBUG