apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 2
  maxReplicas: 15
  metrics:
  # CPU utilization target
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  # Memory utilization target
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
  # Custom metric: Requests per second
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
        selector:
          matchLabels:
            app.kubernetes.io/name: frontend
      target:
        type: AverageValue
        averageValue: "200"
  # Custom metric: WebSocket connections
  - type: Pods
    pods:
      metric:
        name: websocket_connections_active
        selector:
          matchLabels:
            app.kubernetes.io/name: frontend
      target:
        type: AverageValue
        averageValue: "100"
  # Custom metric: Node.js event loop lag
  - type: Pods
    pods:
      metric:
        name: nodejs_eventloop_lag_seconds
        selector:
          matchLabels:
            app.kubernetes.io/name: frontend
      target:
        type: AverageValue
        averageValue: "0.1"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 15
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 3
        periodSeconds: 30
      selectPolicy: Max