apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: market-service-hpa
  labels:
    app.kubernetes.io/name: market-service
    app.kubernetes.io/component: marketplace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: market-service
  minReplicas: 2
  maxReplicas: 20
  metrics:
  # CPU utilization target
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  # Memory utilization target
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  # Custom metric: Requests per second
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
        selector:
          matchLabels:
            app.kubernetes.io/name: market-service
      target:
        type: AverageValue
        averageValue: "100"
  # Custom metric: Queue depth for async processing
  - type: Pods
    pods:
      metric:
        name: rabbitmq_queue_messages
        selector:
          matchLabels:
            app.kubernetes.io/name: market-service
            queue: "market-processing"
      target:
        type: AverageValue
        averageValue: "50"
  # Custom metric: Database connection pool utilization
  - type: Pods
    pods:
      metric:
        name: hikaricp_connections_active
        selector:
          matchLabels:
            app.kubernetes.io/name: market-service
      target:
        type: AverageValue
        averageValue: "15"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 4
        periodSeconds: 60
      selectPolicy: Max