apiVersion: v1
kind: Service
metadata:
  name: market-service
  labels:
    app.kubernetes.io/name: market-service
    app.kubernetes.io/component: marketplace
spec:
  type: ClusterIP
  ports:
  - port: 8084
    targetPort: 8084
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: market-service