server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
    min-response-size: 1024
  http2:
    enabled: true

spring:
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 30s
        pool:
          type: elastic
          max-idle-time: 15s
          max-life-time: 60s
      httpserver:
        idle-timeout: 30s
      routes:
        # Auth Service
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: JwtAuthenticationFilter
        
        # Social Service
        - id: social-service
          uri: http://social-service:8082
          predicates:
            - Path=/social/**
          filters:
            - name: JwtAuthenticationFilter
        
        # Booking Service
        - id: booking-service
          uri: http://booking-service:8083
          predicates:
            - Path=/bookings/**
          filters:
            - name: JwtAuthenticationFilter
        
        # Market Service
        - id: market-service
          uri: http://market-service:8084
          predicates:
            - Path=/market/**
          filters:
            - name: JwtAuthenticationFilter
        
        # Chat Service
        - id: chat-service
          uri: http://chat-service:8085
          predicates:
            - Path=/chat/**
          filters:
            - name: JwtAuthenticationFilter
        
        # Notification Service
        - id: notification-service
          uri: http://notification-service:8086
          predicates:
            - Path=/notify/**
          filters:
            - name: JwtAuthenticationFilter
        
        # Trip Planning Service
        - id: trip-planning-service
          uri: http://trip-planning-service:8087
          predicates:
            - Path=/trips/**
          filters:
            - name: JwtAuthenticationFilter
        
        # AI Service
        - id: ai-service
          uri: http://ai-service:8088
          predicates:
            - Path=/api/v1/ai/**
          filters:
            - name: JwtAuthenticationFilter
            - StripPrefix=2
        
        # Search Service
        - id: search-service
          uri: http://search-service:8091
          predicates:
            - Path=/search/**
          filters:
            - name: JwtAuthenticationFilter
        
        # Config Service
        - id: config-service
          uri: http://config-service:8092
          predicates:
            - Path=/api/v1/config/**
          filters:
            - name: JwtAuthenticationFilter
            - StripPrefix=2
        
        # Admin Service
        - id: admin-service
          uri: http://admin-service:8090
          predicates:
            - Path=/api/v1/admin/**
          filters:
            - name: JwtAuthenticationFilter
            - StripPrefix=2
        
        # Analytics Service
        - id: analytics-service
          uri: http://analytics-service:8093
          predicates:
            - Path=/api/v1/analytics/**
          filters:
            - name: JwtAuthenticationFilter
            - StripPrefix=2
        
        # Emergency Service
        - id: emergency-service
          uri: http://emergency-service:8089
          predicates:
            - Path=/api/v1/emergency/**
          filters:
            - StripPrefix=2
      
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      default-filters:
         - name: AcceptLanguageFilter
         - name: ETagFilter
         - name: AddResponseHeader
           args:
             name: Cache-Control
             value: "public, max-age=300"
         - name: AddResponseHeader
           args:
             name: X-Content-Type-Options
             value: nosniff
         - name: AddResponseHeader
           args:
             name: X-Frame-Options
             value: DENY
         - name: AddResponseHeader
           args:
             name: Vary
             value: "Accept-Encoding, Authorization, Accept-Language"

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

# Logging configuration
logging:
  level:
    com.hopngo.gateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Redis configuration (for future rate limiting)
spring.data.redis:
  host: localhost
  port: 6379
  timeout: 2000ms
  lettuce:
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0