apiVersion: v2
name: hopngo-infrastructure
description: A Helm chart for HopNGo infrastructure components
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - hopngo
  - travel
  - infrastructure
  - microservices

maintainers:
  - name: HopNGo Team
    email: team@hopngo.com

dependencies:
  - name: postgresql
    version: "12.12.10"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
    
  - name: mongodb
    version: "14.4.4"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mongodb.enabled
    
  - name: redis
    version: "18.4.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
    
  - name: rabbitmq
    version: "12.5.6"
    repository: "https://charts.bitnami.com/bitnami"
    condition: rabbitmq.enabled
    
  - name: prometheus
    version: "25.8.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
    
  - name: grafana
    version: "7.0.19"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
    
  - name: ingress-nginx
    version: "4.8.3"
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: nginx-ingress.enabled
    
  - name: cert-manager
    version: "1.13.3"
    repository: "https://charts.jetstack.io"
    condition: cert-manager.enabled

annotations:
  category: Infrastructure
  licenses: Apache-2.0