apiVersion: v1
kind: ConfigMap
metadata:
  name: emergency-service-config
  labels:
    app.kubernetes.io/name: emergency-service
    app.kubernetes.io/component: emergency
data:
  database.url: "jdbc:postgresql://postgresql:5432/hopngo"
  rabbitmq.host: "rabbitmq"
  rabbitmq.port: "5672"
  application.yml: |
    server:
      port: 8086
    spring:
      application:
        name: emergency-service
      profiles:
        active: k8s
      jpa:
        hibernate:
          ddl-auto: validate
        show-sql: false
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
      rabbitmq:
        port: 5672
        virtual-host: /
        connection-timeout: 15000
        template:
          retry:
            enabled: true
            initial-interval: 1000
            max-attempts: 3
            multiplier: 2
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      endpoint:
        health:
          probes:
            enabled: true
          show-details: always
    jwt:
      public-key-location: classpath:jwt-public.key
    google:
      maps:
        base-url: https://maps.googleapis.com/maps/api
    emergency:
      response-time-threshold: 300
      auto-escalation-enabled: true
    logging:
      level:
        com.hopngo.emergency: INFO
        org.springframework.amqp: DEBUG