apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: emergency-service-hpa
  labels:
    app.kubernetes.io/name: emergency-service
    app.kubernetes.io/component: emergency
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: emergency-service
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30