apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-service-config
  labels:
    app.kubernetes.io/name: chat-service
    app.kubernetes.io/component: messaging
data:
  mongodb.database: "hopngo_chat"
  rabbitmq.host: "rabbitmq"
  rabbitmq.port: "5672"
  application.yml: |
    server:
      port: 8085
    spring:
      application:
        name: chat-service
      profiles:
        active: k8s
      data:
        mongodb:
          database: hopngo_chat
      rabbitmq:
        port: 5672
        virtual-host: /
        connection-timeout: 15000
        template:
          retry:
            enabled: true
            initial-interval: 1000
            max-attempts: 3
            multiplier: 2
      websocket:
        allowed-origins:
          - "http://localhost:3000"
          - "http://hopngo.local"
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      endpoint:
        health:
          probes:
            enabled: true
          show-details: always
    jwt:
      public-key-location: classpath:jwt-public.key
    logging:
      level:
        com.hopngo.chat: INFO
        org.springframework.web.socket: DEBUG
        org.springframework.amqp: DEBUG