apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  labels:
    app.kubernetes.io/name: chat-service
    app.kubernetes.io/component: messaging
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: chat-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: chat-service
        app.kubernetes.io/component: messaging
    spec:
      containers:
      - name: chat-service
        image: ghcr.io/hopngo/chat-service:latest
        ports:
        - containerPort: 8085
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: SPRING_DATA_MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: connection-string
        - name: JWT_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: public-key
        - name: SPRING_RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: chat-service-config
              key: rabbitmq.host
        - name: SPRING_RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: username
        - name: SPRING_RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8085
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8085
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      restartPolicy: Always