apiVersion: v1
kind: Service
metadata:
  name: chat-service
  labels:
    app.kubernetes.io/name: chat-service
    app.kubernetes.io/component: messaging
spec:
  type: ClusterIP
  ports:
  - port: 8085
    targetPort: 8085
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: chat-service