server:
  port: 8093

spring:
  application:
    name: support-service
  datasource:
    url: jdbc:postgresql://localhost:5432/hopngo_support
    username: ${DB_USERNAME:hopngo}
    password: ${DB_PASSWORD:hopngo123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8081/auth/realms/hopngo}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.hopngo.support: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

support:
  notification:
    service-url: ${NOTIFICATION_SERVICE_URL:http://localhost:8084}
  admin:
    default-agents:
      - admin@hopngo.com
      - support@hopngo.com
  tickets:
    auto-close-days: 30
    escalation-hours: 24

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method