server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: hopngo-backend
  
  profiles:
    active: local
  
  datasource:
    url: jdbc:postgresql://localhost:5432/hopngo
    username: hopngo_user
    password: hopngo_password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
  
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
  
  security:
    jwt:
      secret: hopngo-jwt-secret-key-change-in-production
      expiration: 86400000 # 24 hours

logging:
  level:
    com.hopngo: INFO
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized