apiVersion: v1
kind: ConfigMap
metadata:
  name: trip-planning-service-config
  labels:
    app.kubernetes.io/name: trip-planning-service
    app.kubernetes.io/component: trip-planning
data:
  database.url: "jdbc:postgresql://postgresql:5432/hopngo"
  redis.host: "redis-master"
  redis.port: "6379"
  application.yml: |
    server:
      port: 8087
    spring:
      application:
        name: trip-planning-service
      profiles:
        active: k8s
      jpa:
        hibernate:
          ddl-auto: validate
        show-sql: false
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
      redis:
        timeout: 2000ms
        lettuce:
          pool:
            max-active: 8
            max-idle: 8
            min-idle: 0
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      endpoint:
        health:
          probes:
            enabled: true
          show-details: always
    jwt:
      public-key-location: classpath:jwt-public.key
    google:
      maps:
        base-url: https://maps.googleapis.com/maps/api
    logging:
      level:
        com.hopngo.tripplanning: INFO
        org.springframework.web.client: DEBUG