apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-planning-service
  labels:
    app.kubernetes.io/name: trip-planning-service
    app.kubernetes.io/component: trip-planning
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: trip-planning-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: trip-planning-service
        app.kubernetes.io/component: trip-planning
    spec:
      containers:
      - name: trip-planning-service
        image: ghcr.io/hopngo/trip-planning-service:latest
        ports:
        - containerPort: 8087
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: trip-planning-service-config
              key: database.url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: password
        - name: JWT_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: public-key
        - name: SPRING_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: trip-planning-service-config
              key: redis.host
        - name: SPRING_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
        - name: GOOGLE_MAPS_API_KEY
          valueFrom:
            secretKeyRef:
              name: maps-secret
              key: google-api-key
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8087
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8087
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      restartPolicy: Always