apiVersion: v1
kind: Service
metadata:
  name: trip-planning-service
  labels:
    app.kubernetes.io/name: trip-planning-service
    app.kubernetes.io/component: trip-planning
spec:
  type: ClusterIP
  ports:
  - port: 8087
    targetPort: 8087
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: trip-planning-service