apiVersion: v1
kind: Service
metadata:
  name: auth-service-preview
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/component: authentication
    service-type: preview
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: auth-service