-- Create itineraries table for trip planning service
CREATE TABLE itineraries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id VARCHAR(255) NOT NULL,
    title VARCHAR(500) NOT NULL,
    days INTEGER NOT NULL CHECK (days >= 1 AND days <= 30),
    budget INTEGER NOT NULL CHECK (budget > 0),
    origins JSONB NOT NULL,
    destinations JSONB NOT NULL,
    plan JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for better query performance
CREATE INDEX idx_itineraries_user_id ON itineraries(user_id);
CREATE INDEX idx_itineraries_user_created ON itineraries(user_id, created_at DESC);
CREATE INDEX idx_itineraries_created_at ON itineraries(created_at DESC);

-- Create function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger to automatically update updated_at on row updates
CREATE TRIGGER update_itineraries_updated_at
    BEFORE UPDATE ON itineraries
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Add comments for documentation
COMMENT ON TABLE itineraries IS 'Stores trip itineraries generated by AI service';
COMMENT ON COLUMN itineraries.id IS 'Unique identifier for the itinerary';
COMMENT ON COLUMN itineraries.user_id IS 'ID of the user who owns this itinerary';
COMMENT ON COLUMN itineraries.title IS 'User-defined title for the itinerary';
COMMENT ON COLUMN itineraries.days IS 'Number of days for the trip (1-30)';
COMMENT ON COLUMN itineraries.budget IS 'Budget for the trip in cents';
COMMENT ON COLUMN itineraries.origins IS 'JSON array of origin locations';
COMMENT ON COLUMN itineraries.destinations IS 'JSON array of destination locations';
COMMENT ON COLUMN itineraries.plan IS 'Generated itinerary plan from AI service';
COMMENT ON COLUMN itineraries.created_at IS 'Timestamp when the itinerary was created';
COMMENT ON COLUMN itineraries.updated_at IS 'Timestamp when the itinerary was last updated';}}}