apiVersion: v1
kind: ConfigMap
metadata:
  name: social-service-config
  labels:
    app.kubernetes.io/name: social-service
    app.kubernetes.io/component: social
data:
  redis.host: "redis-master"
  redis.port: "6379"
  mongodb.database: "hopngo_social"
  application.yml: |
    server:
      port: 8082
    spring:
      application:
        name: social-service
      profiles:
        active: k8s
      data:
        mongodb:
          database: hopngo_social
      redis:
        timeout: 2000ms
        lettuce:
          pool:
            max-active: 8
            max-idle: 8
            min-idle: 0
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      endpoint:
        health:
          probes:
            enabled: true
          show-details: always
    jwt:
      public-key-location: classpath:jwt-public.key
    logging:
      level:
        com.hopngo.social: INFO
        org.springframework.data.mongodb: DEBUG