apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-service
  labels:
    app.kubernetes.io/name: social-service
    app.kubernetes.io/component: social
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: social-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: social-service
        app.kubernetes.io/component: social
    spec:
      containers:
      - name: social-service
        image: ghcr.io/hopngo/social-service:latest
        ports:
        - containerPort: 8082
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: SPRING_DATA_MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: connection-string
        - name: JWT_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: public-key
        - name: SPRING_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: social-service-config
              key: redis.host
        - name: SPRING_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      restartPolicy: Always