apiVersion: v1
kind: Service
metadata:
  name: social-service
  labels:
    app.kubernetes.io/name: social-service
    app.kubernetes.io/component: social
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: social-service