name: CI - Build & Test

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  java-services:
    name: Build & Test Java Services
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service: [
          'auth-service',
          'booking-service', 
          'chat-service',
          'emergency-service',
          'gateway',
          'notification-service',
          'social-service',
          'trip-planning-service',
          'ai-service',
          'market-service'
        ]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build and test ${{ matrix.service }}
      run: |
        cd ${{ matrix.service }}
        ./mvnw -B clean verify
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.service }}
        path: ${{ matrix.service }}/target/surefire-reports/
        
  frontend:
    name: Build & Test Frontend
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8
        
    - name: Cache pnpm dependencies
      uses: actions/cache@v4
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-pnpm-
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Lint frontend
      run: |
        cd frontend
        pnpm lint
        
    - name: Build frontend
      run: |
        cd frontend
        pnpm build
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: frontend/.next/
        
  lint:
    name: Lint & Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: Run ESLint
      run: pnpm lint
      
    - name: Run Prettier check
      run: pnpm prettier --check .
      
  summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [java-services, frontend, lint]
    if: always()
    
    steps:
    - name: Check all jobs status
      run: |
        if [[ "${{ needs.java-services.result }}" == "success" && "${{ needs.frontend.result }}" == "success" && "${{ needs.lint.result }}" == "success" ]]; then
          echo "✅ All CI checks passed!"
        else
          echo "❌ Some CI checks failed:"
          echo "Java Services: ${{ needs.java-services.result }}"
          echo "Frontend: ${{ needs.frontend.result }}"
          echo "Lint: ${{ needs.lint.result }}"
          exit 1
        fi