apiVersion: v1
kind: Service
metadata:
  name: ai-service
  labels:
    app.kubernetes.io/name: ai-service
    app.kubernetes.io/component: ai
spec:
  type: ClusterIP
  ports:
  - port: 8088
    targetPort: 8088
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: ai-service